/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaschmed;

/**
 *
 * @author Francesca Kaschnig
 */
public class newPatient extends javax.swing.JDialog {
    
    Benutzeroberflaeche flaeche = new Benutzeroberflaeche ();
    
    
    
    
    public void studentenanlegen(String vorname, String nachname, int iD, int telefonNr, int sVN, String geschlecht){
        try {
            boolean vorhanden = false;
            
            vorhanden = query1.containsKey(nummer);
            
            
            if (vorhanden == false) {
                
                Patient newpat = new Patient(String vorname, String nachname, int iD, int telefonNr, int sVN, String geschlecht);
                meineTM.put(nummer, newstud);
                System.out.println("Der Student : " + newstud + "mit der Matrikelnummer: " + nummer + "wurde hinzugefügt!");
            } else if (vorhanden == true) {
                throw new MyExceptions(Enum.SCHONVORHANDEN, "Die Matrikelnummer ist bereits vergeben!");

            }
        } catch (MyExceptions a) {
            switch (a.x) {
                case SCHONVORHANDEN:
                    System.out.println("Die Matrikelnummer ist schon vorhanden!");
            }
        }
    }

    /**
     * Creates new form newPatient
     */
    public newPatient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelTitel = new javax.swing.JLabel();
        angabe = new javax.swing.JLabel();
        patientenID = new javax.swing.JLabel();
        neuerVorname = new javax.swing.JLabel();
        neuerNachname = new javax.swing.JLabel();
        neueSVN = new javax.swing.JLabel();
        patientID = new javax.swing.JTextField();
        patientVN = new javax.swing.JTextField();
        patientNN = new javax.swing.JTextField();
        patientSVN = new javax.swing.JTextField();
        addPatient = new javax.swing.JButton();
        exitAdd = new javax.swing.JButton();
        neuesGeschlecht = new javax.swing.JLabel();
        maennlich = new javax.swing.JRadioButton();
        weiblich = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titelTitel.setText("Patient anlegen:");

        angabe.setText("Bitte füllen Sie alle Felder aus!");

        patientenID.setText("PatientenID:");

        neuerVorname.setText("Vorname:");

        neuerNachname.setText("Nachname:");

        neueSVN.setText("SVN:");

        patientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDActionPerformed(evt);
            }
        });

        patientNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNNActionPerformed(evt);
            }
        });

        patientSVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSVNActionPerformed(evt);
            }
        });

        addPatient.setText("Add");
        addPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientActionPerformed(evt);
            }
        });

        exitAdd.setText("Exit");
        exitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAddActionPerformed(evt);
            }
        });

        neuesGeschlecht.setText("Geschlecht:");

        maennlich.setText("männlich");
        maennlich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maennlichActionPerformed(evt);
            }
        });

        weiblich.setText("weiblich");
        weiblich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weiblichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titelTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(exitAdd)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(addPatient))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(neueSVN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(patientSVN, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patientenID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(neuerVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(neuerNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patientVN, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientNN, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(neuesGeschlecht, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(maennlich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weiblich)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titelTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(angabe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientenID)
                    .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuerVorname)
                    .addComponent(patientVN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neuerNachname))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuesGeschlecht)
                    .addComponent(maennlich)
                    .addComponent(weiblich))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neueSVN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientSVN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatient)
                    .addComponent(exitAdd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientSVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSVNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientSVNActionPerformed

    private void exitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAddActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitAddActionPerformed

    private void patientNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNNActionPerformed

    private void weiblichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weiblichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weiblichActionPerformed

    private void maennlichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maennlichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maennlichActionPerformed

    private void patientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDActionPerformed

    private void addPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientActionPerformed
       String id = patientID.getText();
       if(id.matches("^[\\d]+")){
       
       }
       String vorname = patientVN.getText();
       String nachname = patientNN.getText();
       int svn = patientSVN.getColumns();
       
       if(maennlich.isSelected()){
       
       
       } else if(weiblich.isSelected()){
       
       }
       
    }//GEN-LAST:event_addPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                newPatient dialog = new newPatient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatient;
    private javax.swing.JLabel angabe;
    private javax.swing.JButton exitAdd;
    private javax.swing.JRadioButton maennlich;
    private javax.swing.JLabel neueSVN;
    private javax.swing.JLabel neuerNachname;
    private javax.swing.JLabel neuerVorname;
    private javax.swing.JLabel neuesGeschlecht;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField patientNN;
    private javax.swing.JTextField patientSVN;
    private javax.swing.JTextField patientVN;
    private javax.swing.JLabel patientenID;
    private javax.swing.JLabel titelTitel;
    private javax.swing.JRadioButton weiblich;
    // End of variables declaration//GEN-END:variables
}
